apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo 2
on:
  workflow_dispatch:
    inputs:
      asdf:
        type: choice
        options:
          - ""
          - adsfasdfa
        default: ""
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
