apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo 4
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 100
          echo "hello world"
on:
  schedule:
    - cron: '51 * * * *'
