apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Example 1

on:
  workflow_dispatch:
   inputs:
     Deployment_version:
       type: string
       default: latest
       required: true
       description: "Specify the version (for example: v1.0, v736) of the application to deploy."
jobs:
 build:
   steps:
     - name: Deploy application
       uses: docker://alpine:3.13
       shell: sh
       run: |
          echo "Starting deployment..."
          # Example deployment command using the provided string parameter
          ./deploy.sh --version ${inputs.deployment_version} --env ${inputs.environment}
          echo "Deployment of version ${inputs.deployment_version} to ${inputs.environment} completed successfully"

