apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Example 1
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Deploy application
        uses: docker://alpine:3.13
        shell: sh
        run: |
          echo "Deployment of version ${{inputs.Deployment_version}}"
