apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      Stringparam:
        type: string
        default: mlcb
      Numberparam:
        type: number
        default: 666
      Boolparam:
        type: boolean
        default: true
      Choiceparam:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt3
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  build2:
    needs: build
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  build3:
    needs: build2
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
