apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      namePsram1:
        type: string
        default: Mariluz
        description: decrip
      bool:
        type: boolean
        default: true
        required: true
        description: desc 2
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
